# Thông số chung cho AMCL
min_particles: 100
max_particles: 5000
kld_err: 0.02
update_min_d: 0.2
update_min_a: 0.5
resample_interval: 2
transform_tolerance: 0.1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# Nguồn dữ liệu từ LiDAR
laser_max_beams: 360
laser_max_range: 30.0
laser_min_range: 0.1
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0

# Mô hình odometry
odom_model_type: "diff"
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2

# Frame IDs
odom_frame_id: "odom"
base_frame_id: "base_link"
global_frame_id: "map"
